language: php

php:
 - '7.1'

cache:
 directories:
 - $CACHE_DIR

install:
 - mkdir -p $CACHE_DIR

before_script:
- cp .env.travis .env
- touch database/database.sqlite
- travis_retry composer self-update
- travis_retry - composer install --prefer-dist  --no-interaction
- php artisan migrate:refresh --seed
- sleep 3

script:
- vendor/bin/phpunit

after_success:
- curl -X GET https://forge.laravel.com/servers/92421/sites/304719/deploy/http?token=fVQ8eUarYRTYFDMJxau7P2pyqofICltZGebnZvmf